version: '{branch}-{build}'
image: Visual Studio 2019

branches:
  only:
    - main

skip_commits:
  files:
    - '*.md'
    - '.github/**'
    - 'source/WebApp/**'

build_script:
- cmd: sl ci