name: Server (.NET) - Edge

on:
  push:
    paths-ignore:
    - '.github/workflows/roslyn-branches.yml'
    - '.github/workflows/web-app*.yml'
    - 'source/WebApp/**'
  pull_request:

jobs:
  build-netfx:
    name: 'Build (.NET Framework)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - run: dotnet build source/NetFramework/Server
    - run: dotnet build source/NetFramework/Tests
    - run: dotnet test source/NetFramework/Tests