name: WebApp (JS)

on:
  push:
    paths:
    - '.github/workflows/web-app.yml'
    - 'source/WebApp/**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/WebApp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'

    - run: npm ci      
    - run: npm run build
    - run: npm test
    
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: __diff_output__
        path: source/WebApp/tests/rendering/__image_snapshots__/__diff_output__
        if-no-files-found: ignore

    - uses: softprops/action-gh-release@v1
      with:
        tag_name: experimental-webapp-release-${{ github.run_number }}
        files: source/WebApp/wwwroot/**
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}