name: WebApp (JS)

on:
  push:
    paths:
    - '.github/workflows/web-app.yml'
    - 'source/WebApp/**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: source/WebApp
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'

    - run: npm ci
    - run: npm run build-ci
    - run: npm test

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: __diff_output__
        path: source/WebApp/tests/rendering/__image_snapshots__/__diff_output__
        if-no-files-found: ignore

    - uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
      with:
        tag_name: experimental-webapp-release-${{ github.run_number }}
        files: source/WebApp/WebApp.zip
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-edge:
    name: Deploy (Edge)
    environment: edge
    runs-on: ubuntu-latest
    steps:

      - uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
        with:
          version: experimental-webapp-release-${{ github.run_number }}
          file: WebApp.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: montudor/action-zip@c25e01d7489d0274569440a2f0281b4569df16bc
        with:
          args: unzip -qq WebApp.zip -d WebApp

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
                az storage blob upload-batch --account-name sharplab -d edge -s WebApp

      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
                az cdn endpoint purge --content-paths /edge/latest --profile-name "SharpLab-CDN" --name sharplab
      - run: |
          Set-ScriptMode -Version 2
          $ErrorActionPreference = 'Stop'
          Invoke-RestMethod -Method POST -Uri 'https://edge.sharplab.io/assets/reload' -Authentication Bearer -Token $(ConvertTo-SecureString '${{ secrets.SHARPLAB_ASSETS_RELOAD_TOKEN }}')
        shell: pwsh